
product_extraction_task:
  description: >
    Extract comprehensive information for the products: {product_1} and {product_2}.
    Gather detailed specifications, features, pricing, availability, and customer reviews.
    Focus on finding accurate and up-to-date information for both products.
  expected_output: >
    A structured report containing detailed information for both products including:
    - Product specifications and features
    - Pricing and availability
    - Customer reviews and ratings
    - Key advantages and disadvantages
  agent: info_extractor

product_comparison_task:
  description: >
    Compare {product_1} and {product_2} based on the extracted information.
    Analyze differences in features, specifications, pricing, and customer satisfaction.
    Identify strengths and weaknesses of each product objectively.
  expected_output: >
    A detailed comparison analysis formatted as markdown including:
    - Side-by-side feature comparison
    - Pros and cons for each product
    - Performance and value analysis
    - Summary of key differences
  agent: comparator

product_recommendation_task:
  description: >
    Based on the comparison analysis and considering user preferences: {user_preferences},
    provide a personalized recommendation between {product_1} and {product_2}.
    Consider factors like budget, intended use, and specific user requirements.
  expected_output: >
    A clear recommendation report including:
    - Recommended product with detailed justification
    - Explanation of why it best fits the user's needs
    - Alternative scenarios where the other product might be better
    - Final advice and next steps for the user
  agent: recommender
